@component('mail::message')
# RC PLASTO TANKS AND PIPES PRIVATE LIMITED Energy And Productivity Report
Dear Sir/Madam
<br>

    Please see the attached report generated by Energy Optimization And Prductivity Monitoring System
    RC PLASTO TANKS AND PIPES PRIVATE LIMITED

Thanks,<br>
{{ /*config('app.name')*/ 'HETA DATAIN' }}
@endcomponent